# Generated by Django 4.1.7 on 2023-05-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='authorUser',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='user_rating',
            new_name='userRating',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_rating',
            new_name='commentRating',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_rating',
            new_name='postRating',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
        migrations.AddField(
            model_name='post',
            name='postType',
            field=models.CharField(choices=[('A', 'статья'), ('N', 'новость')], default='article', max_length=1),
        ),
    ]
