# Generated by Django 4.1.7 on 2023-05-04 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_user_author_authoruser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='postcomment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='news.post'),
        ),
    ]
